#!/usr/bin/env node
/**
 * GhostImprint Courtroom Evidence Dossier Generator
 * Compiles the measured audit result into a sealed report. Unmeasured
 * layers are listed as such. No hardcoded match counts or verdicts.
 */

const fs = require('fs');
const path = require('path');
const child = require('child_process');
const core = require('./ghostimprint');

function collectAuditJson(targetDir) {
  const auditScript = path.join(__dirname, 'ghostimprint-audit.js');
  const out = child.spawnSync(process.execPath, [auditScript, '--target', targetDir, '--json'], { encoding: 'utf8' });
  if (out.status !== 0) {
    console.error((out.stderr || 'Audit failed with no output.').trim());
    process.exit(out.status || 1);
  }
  return JSON.parse(out.stdout);
}

function layerLine(name, layer) {
  if (layer.status === 'MEASURED') {
    if (typeof layer.detail === 'string') return `* **${name}:** MEASURED. ${layer.detail}.`;
    let detail;
    if (layer.matchedFiles !== undefined) detail = `${layer.matchedFiles} files`;
    else if (layer.matched !== undefined && layer.tested !== undefined) detail = `${layer.matched}/${layer.tested} literals`;
    else if (layer.matched !== undefined) detail = layer.matched ? 'coefficients present' : 'coefficients absent';
    else if (layer.agreed !== undefined) detail = `${layer.agreed}/${layer.tested} sites agree`;
    else if (layer.verified !== undefined) detail = layer.verified ? `anchor verified (commit ${String(layer.commit).slice(0, 12)})` : `anchor recorded but not verified: ${layer.reason || ''}`;
    else detail = `${layer.filesWithMarkers || 0} files, ${layer.totalMarkers || 0} markers`;
    return `* **${name}:** MEASURED. Observed ${detail}.`;
  }
  return `* **${name}:** UNMEASURED. ${layer.reason || ''}`;
}

function generateExhibitReport(targetDir = process.cwd()) {
  const metadata = core.discoverProjectMetadata();
  const dateStr = new Date().toISOString();
  const audit = collectAuditJson(targetDir);
  const L = audit.layers;

  const report = `# Forensic Evidence Exhibit: Cryptographic Code Provenance Verification

**Exhibit Reference:** GI-EXHIBIT-${Date.now().toString(36).toUpperCase()}
**Date of Verification:** ${dateStr}
**Verified Author Identity:** ${metadata.author}
**Canonical Upstream Repository:** ${metadata.repo}
**Audited Target Codebase:** ${audit.target}
**Identity Source:** ${audit.identitySource}

## Executive Summary
This document reports the measured output of the GhostImprint audit engine against the target codebase. Only MEASURED layers contribute to the verdict below. UNMEASURED layers are excluded, never counted as matches. Population error rates are pending corpus baselining; this report makes no Daubert admissibility claim on its own.

## Measured Layer Findings

${layerLine('Layer 0 Honeypot Decoys', L.layer0HoneypotDecoys)}
${layerLine('Layer 1 Crypto Words', L.layer1CryptoWords)}
${layerLine('Layer 2 Ratio Coefficients', L.layer2RatioCoefficients)}
${layerLine('Layer 3 Unicode Channels', L.layer3UnicodeChannels)}
${layerLine('Layer 4 Stylometry', L.layer4Stylometry)}
${layerLine('Layer 5 AST Topology', L.layer5AstTopology)}
${layerLine('Layer 6 Soft Cluster', L.layer6SoftCluster)}
${layerLine('Layer 7 Remote Oracle', L.layer7RemoteOracle)}
${layerLine('Layer 8 Temporal Anchor', L.layer8TemporalAnchor)}

## Verdict (Measured Evidence Only)
* **Verdict:** ${audit.verdict}
* **Files Scanned:** ${audit.totalFilesScanned}
* **Honesty Note:** ${audit.honestyNote}

## Independent Sandbox Reproduction Protocol
Any court-appointed technical master or opposing counsel can independently reproduce these findings on an air-gapped machine:

\`\`\`bash
# 1. Execute independent verification using node standard runtime
node .skills/ghostimprint/scripts/ghostimprint-audit.js --target ./target-codebase --json
\`\`\`

---
*Report sealed and generated by GhostImprint Engine v5 from measured audit output.*
`;

  const outputPath = path.join(process.cwd(), 'FORENSIC_EXHIBIT_REPORT.md');
  fs.writeFileSync(outputPath, report, 'utf8');
  console.log(`\n[OK] Forensic evidence dossier generated at: ${outputPath}`);
  console.log(`Verdict (measured only): ${audit.verdict}`);
  return outputPath;
}

const args = process.argv.slice(2);
const target = args[0] || process.cwd();
generateExhibitReport(target);
